# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('HotelId', models.TextField(blank=True, db_column='hotelId', primary_key=True, serialize=False)),
                ('Destination', models.TextField(blank=True, db_column='destination', null=True)),
                ('Area', models.TextField(blank=True, db_column='area', null=True)),
                ('HotelName', models.TextField(blank=True, db_column='hotelName', null=True)),
                ('HotelAddress', models.TextField(blank=True, db_column='address', null=True)),
                ('HotelAmens', models.TextField(blank=True, db_column='hotelAmenities', null=True)),
                ('HotelServices', models.TextField(blank=True, db_column='hotelServices', null=True)),
                ('HotelRoomTypes', models.TextField(blank=True, db_column='hotelRoomTypes', null=True)),
                ('PriceByDate', models.TextField(blank=True, db_column='priceByDate', null=True)),
                ('HotelPictures', models.ImageField(default='hotelPics/avatar.jpg', upload_to='hotelPics/')),
                ('HotelDescription', models.TextField(blank=True, db_column='hotelDescription', null=True)),
                ('ownerId', models.TextField(db_column='ownerId', default='Overnightasia')),
            ],
            options={
                'db_table': 'HotelInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchantID', models.AutoField(primary_key=True, serialize=False)),
                ('merchantName', models.TextField(db_column='merchantname')),
                ('email', models.TextField(default=' ')),
                ('phone', models.TextField(default=' ')),
                ('streetAddr', models.TextField(default=' ')),
                ('unit', models.TextField(default=' ')),
                ('city', models.TextField(default=' ')),
                ('state', models.TextField(default=' ')),
                ('zip', models.TextField(default=' ')),
                ('country', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'Merchant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageId', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.TextField(db_column='packageName')),
                ('packageDesc', models.TextField(db_column='description')),
                ('price', models.FloatField(db_column='price', default=0)),
                ('roomType', models.TextField(blank=True, db_column='roomType')),
                ('serviceList', models.TextField(db_column='serviceList')),
                ('discountPercent', models.FloatField(default=0)),
                ('hotelTax', models.FloatField(default=0)),
                ('serviceCharge', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'PackageInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False)),
                ('roomType', models.TextField(blank=True, db_column='roomType')),
                ('hotelName', models.TextField(blank=True, db_column='hotelName', null=True)),
                ('destination', models.TextField(blank=True, db_column='destination', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ratePerNight', models.FloatField(default=0)),
                ('airportTransfer', models.FloatField(default=0)),
                ('discountPercent', models.FloatField(default=0)),
                ('hotelTax', models.FloatField(default=0)),
                ('serviceCharge', models.FloatField(default=0)),
                ('ownerId', models.TextField(db_column='ownerId', default='Overnightasia')),
            ],
            options={
                'db_table': 'RoomInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default=' ')),
                ('fname', models.TextField(default=' ')),
                ('lname', models.TextField(default=' ')),
                ('email', models.TextField(default=' ')),
                ('phone', models.TextField(default=' ')),
                ('homeAirport', models.TextField(default=' ')),
                ('streetAddr', models.TextField(default=' ')),
                ('unit', models.TextField(default=' ')),
                ('city', models.TextField(default=' ')),
                ('state', models.TextField(default=' ')),
                ('zip', models.TextField(default=' ')),
                ('country', models.TextField(default=' ')),
                ('gender', models.TextField(default='male')),
                ('travellerPictures', models.ImageField(default='img/300x300.png', upload_to='travellerPics/')),
            ],
            options={
                'db_table': 'Traveller',
                'managed': True,
            },
        ),
    ]
