# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('discountPercent', models.FloatField(default=0)),
                ('hotelTax', models.FloatField(default=0)),
                ('serviceCharge', models.FloatField(default=0)),
                ('airportTransfer', models.FloatField(default=0)),
                ('ratePerNight', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverApp.HotelInfo')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverApp.Merchant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverApp.RoomInfo')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'HotelAvailability',
            },
        ),
    ]
