# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0005_bookinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_actie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
