# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0006_auto_20160619_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_actie',
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
